### ISSUE TITLE
Untrack unwanted folders and files

### ISSUE THREAD

**Issue by AlexIliescu11** [alinaitschool/itschool#2]
Please consider to untrack `.idea` package. This can lead to several problems in the future.
Some tips can be found [here](https://stackoverflow.com/questions/6964297/untrack-files-from-git-temporarily).

![image](https://github.com/alinaitschool/itschool/assets/120710343/95e0906b-5a2f-49fe-89b4-d581bfa7877e)

**Comment by alinaitschool** [comment]
resolved
